---
title: "Objectify Those Brussels Sprouts"
type: "challenge"
description: "Learn the basics of Object Orientation through our favorite recipe ingredient."
visibility: "onsite"
ignore:
- "brussels-sprouts-oo.md"
